language: python

python:
   - "3.4"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install -r requirements.txt
    - pip install Flask
    - pip install Flask-SQLAlchemy
    - apt-get install python3-pymysql
    - apt-get install mysql-server

before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version

script:
    - date
    - make clean test
    - cat tests.tmp
