language: python

python:
   - "3.4"

services:
    - postgresql

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install -r app/requirements.txt
    - pip install Flask
    - pip install Flask-SQLAlchemy


before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version
    - psql -c 'create database swe_test;' -U postgres

script:
    - date
    - ls -al
    - make clean test
    - cat tests.tmp
