version: '2'
services:
    db:
      image: postgres

    web:
      build: .
      ports:
       - "5000:5000"
      volumes:
       - .:/production
      hostname: myappserver
      depends_on:
       - db

